name: Validate YAML

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '.github/workflows/validate_yaml.yml'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint all YAML files
        run: |
          yamllint **/*.yml
          yamllint **/*.yaml
