name: Validate Book YAML

on:
  push:
    paths:
      - 'the_book_v1.0.yaml'
      - '.github/workflows/validate_yaml.yml'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint the master YAML
        run: yamllint the_book_v1.0.yaml
