name: Validate Book YAML

on:
  push:
    paths:
      - the_book_v1.0.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate YAML
        run: yamllint the_book_v1.0.yaml
